//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageResizer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageResizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片高度 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像裁剪器 的本地化字符串。
        /// </summary>
        public static string ImageResizer {
            get {
                return ResourceManager.GetString("ImageResizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （自动） 的本地化字符串。
        /// </summary>
        public static string Input_Auto {
            get {
                return ResourceManager.GetString("Input_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择尺寸预设 的本地化字符串。
        /// </summary>
        public static string Input_Content {
            get {
                return ResourceManager.GetString("Input_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Input_Custom {
            get {
                return ResourceManager.GetString("Input_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GIF 动画可能无法裁剪。 的本地化字符串。
        /// </summary>
        public static string Input_GifWarning {
            get {
                return ResourceManager.GetString("Input_GifWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略图片方向(_O) 的本地化字符串。
        /// </summary>
        public static string Input_IgnoreOrientation {
            get {
                return ResourceManager.GetString("Input_IgnoreOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图片元数据 的本地化字符串。
        /// </summary>
        public static string Input_RemoveMetadata {
            get {
                return ResourceManager.GetString("Input_RemoveMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接覆写原图(_E) 的本地化字符串。
        /// </summary>
        public static string Input_Replace {
            get {
                return ResourceManager.GetString("Input_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行(_R) 的本地化字符串。
        /// </summary>
        public static string Input_Resize {
            get {
                return ResourceManager.GetString("Input_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅缩小图片(_M) 的本地化字符串。
        /// </summary>
        public static string Input_ShrinkOnly {
            get {
                return ResourceManager.GetString("Input_ShrinkOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 的本地化字符串。
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用设置 的本地化字符串。
        /// </summary>
        public static string OK_Tooltip {
            get {
                return ResourceManager.GetString("OK_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Open_settings {
            get {
                return ResourceManager.GetString("Open_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流畅 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有图片文件 的本地化字符串。
        /// </summary>
        public static string PictureFilter {
            get {
                return ResourceManager.GetString("PictureFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （默认） 的本地化字符串。
        /// </summary>
        public static string PngInterlaceOption_Default {
            get {
                return ResourceManager.GetString("PngInterlaceOption_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string PngInterlaceOption_Off {
            get {
                return ResourceManager.GetString("PngInterlaceOption_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string PngInterlaceOption_On {
            get {
                return ResourceManager.GetString("PngInterlaceOption_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作中…… 的本地化字符串。
        /// </summary>
        public static string Progress_MainInstruction {
            get {
                return ResourceManager.GetString("Progress_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止(_S) 的本地化字符串。
        /// </summary>
        public static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {0} 小时 {1} 分。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_HourMinute {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HourMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {0} 小时 {1} 分。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_HourMinutes {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HourMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {0} 小时 {1} 分。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_HoursMinute {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HoursMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {0} 小时 {1} 分。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_HoursMinutes {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {1} 分 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_MinuteSecond {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinuteSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {1} 分 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_MinuteSeconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinuteSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {1} 分 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_MinutesSecond {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinutesSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {1} 分 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_MinutesSeconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_Second {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 {2} 秒。 的本地化字符串。
        /// </summary>
        public static string Progress_TimeRemaining_Seconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像裁剪器 的本地化字符串。
        /// </summary>
        public static string Resize_Tooltip {
            get {
                return ResourceManager.GetString("Resize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Resize_Type {
            get {
                return ResourceManager.GetString("Resize_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Fill {
            get {
                return ResourceManager.GetString("ResizeFit_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充到 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Fill_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Fill_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Fit {
            get {
                return ResourceManager.GetString("ResizeFit_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Fit_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Fit_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉伸 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Stretch {
            get {
                return ResourceManager.GetString("ResizeFit_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉伸到 的本地化字符串。
        /// </summary>
        public static string ResizeFit_Stretch_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Stretch_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厘米 的本地化字符串。
        /// </summary>
        public static string ResizeUnit_Centimeter {
            get {
                return ResourceManager.GetString("ResizeUnit_Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英寸 的本地化字符串。
        /// </summary>
        public static string ResizeUnit_Inch {
            get {
                return ResourceManager.GetString("ResizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string ResizeUnit_Percent {
            get {
                return ResourceManager.GetString("ResizeUnit_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        public static string ResizeUnit_Pixel {
            get {
                return ResourceManager.GetString("ResizeUnit_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Results_Close {
            get {
                return ResourceManager.GetString("Results_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片调整大小失败 的本地化字符串。
        /// </summary>
        public static string Results_MainInstruction {
            get {
                return ResourceManager.GetString("Results_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小 的本地化字符串。
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乘号 的本地化字符串。
        /// </summary>
        public static string Times_Symbol {
            get {
                return ResourceManager.GetString("Times_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值必须介于 &apos;{0}&apos; 和 &apos;{1}&apos; 之间。 的本地化字符串。
        /// </summary>
        public static string ValueMustBeBetween {
            get {
                return ResourceManager.GetString("ValueMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片宽度 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
