//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerToys.Run.Plugin.TimeDate.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerToys.Run.Plugin.TimeDate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 复制 (Ctrl+C) 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_CopyToClipboard {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Date {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期和时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DateAndTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期和时间 UTC 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DateAndTimeUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DateAndTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Day {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月日 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DayMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日（每月） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DayOfMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日（每星期） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DayOfWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日（每年） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_DayOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纪元 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Era {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纪元缩写 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_EraAbbreviation {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_EraAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用前缀：“u” 表示 Unix 时间戳，“ft” 表示 Windows 文件时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_ErrorResultSubTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ErrorResultSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误: 数字输入无效 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_ErrorResultTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ErrorResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Hour {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO 8601 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Iso8601 {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO 8601 UTC 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Iso8601Utc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601Utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO 8601 +时区 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Iso8601Zone {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO 8601 UTC +时区 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Iso8601ZoneUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601ZoneUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Millisecond {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Minute {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月份 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Month {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月（每年） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_MonthOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_MonthOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年月 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_MonthYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Now {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在（UTC） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_NowUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_NowUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取时间与日期，支持自定义时间戳（比如：“当前” “月份” “时间::{1}” “星期::{0}”） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_plugin_description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_plugin_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RFC1123 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Rfc1123 {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Rfc1123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for; and; nor; but; or; so; 与; 和; 或; 是; 的; 几; 什么 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Search_ConjunctionList {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Search_ConjunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagDate {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期; 现在 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagDateNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年份; 时代; 日期 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagEra {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前年份; 当前时代; 当前日期; 现在 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagEraNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagEraNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期和时间; 时间和日期 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagFormat {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期和时间; 当前时间和日期; 现在 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagFormatNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagFormatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间; 现在 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SearchTagTimeNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Second {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期显示日月名称 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingDateWithWeekday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingDateWithWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 针对 “日期” 和 “现在” 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingDateWithWeekday_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingDateWithWeekday_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局搜索时隐藏 “数字输入无效” 结果 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingHideNumberMessageOnGlobalQuery {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingHideNumberMessageOnGlobalQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局搜索只显示 “时间” “日期” “现在” 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无论如何，搜索的第一个字必须对上才能搜到 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间显示秒数 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingTimeWithSeconds {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingTimeWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 针对 “时间” 和 “现在” 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SettingTimeWithSeconds_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingTimeWithSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击或按 Ctrl+C 复制 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_SubTitleNote {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SubTitleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Time {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间（UTC） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_TimeUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_TimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备用关键字： 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_ToolTipAlternativeSearchTag {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ToolTipAlternativeSearchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用时间格式：YYYY-MM-DD hh:mm:ss 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_UniversalTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_UniversalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unix 纪元时间 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Unix {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期（每月） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_WeekOfMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WeekOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期（每年） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_WeekOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WeekOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 文件时间（64 位整数） 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_WindowsFileTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WindowsFileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年份 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_Year {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Year", resourceCulture);
            }
        }
    }
}
